# Generated by Django 2.0.3 on 2018-04-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default='', max_length=500, verbose_name='链接'),
        ),
    ]
